name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DIRECTORY_PATH: "/github/workspace"
  TESTING_ENVIRONMENT: "Staging"
  PRODUCTION_ENVIRONMENT: "YourName" # Replace with your name

jobs:
  ci-cd-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Stage
      run: |
        echo "Fetch the source code from the directory path specified by the environment variable: $DIRECTORY_PATH"
        echo "Compile the code and generate any necessary artefacts"

    - name: Test Stage
      run: |
        echo "Unit tests"
        echo "Integration tests"

    - name: Code Quality Check Stage
      run: |
        echo "Check the quality of the code"

    - name: Deploy Stage
      run: |
        echo "Deploy the application to a testing environment specified by the environment variable: $TESTING_ENVIRONMENT"

    - name: Approval Stage
      run: |
        echo "Waiting for manual approval..."
        sleep 10

    - name: Deploy to Production Stage
      run: |
        echo "Deploying the application to the production environment: $PRODUCTION_ENVIRONMENT"
